<Project Sdk="Microsoft.NET.Sdk">


	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<Title>KamiYomu MultiSource – MangaThemesia</Title>
		<Description>A specialized crawler library for extracting manga data from MangaThemesia‑based websites.
Built on KamiYomu.CrawlerAgents.Core, it delivers fast and reliable search, structured metadata parsing, and seamless integration with the KamiYomu ecosystem. The library standardizes interaction with MangaThemesia endpoints, ensuring consistent behavior across all supported sources.</Description>
		<Authors>KamiYomu</Authors>
		<Owners>KamiYomu</Owners>
		<PackageProjectUrl>https://gitea.kamiyomu.com/kamiyomu/KamiYomu.CrawlerAgents.MangaThemesia</PackageProjectUrl>
		<RepositoryUrl>https://gitea.kamiyomu.com/kamiyomu/KamiYomu.CrawlerAgents.MangaThemesia</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>kamiyomu;manga-download;MangaThemesia</PackageTags>
		<PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
		<PackageIconUrl>https://gitea.kamiyomu.com/kamiyomu/KamiYomu.CrawlerAgents.MangaThemesia/raw/branch/main/src/KamiYomu.CrawlerAgents.MangaThemesia/Resources/logo.png</PackageIconUrl>
		<PackageIcon>Resources/logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Resources\logo.png" Pack="true" PackagePath="Resources/" />
		<None Include="..\..\README.md" Link="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<IncludeSymbols>True</IncludeSymbols>
		<IncludeSource>True</IncludeSource>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="KamiYomu.CrawlerAgents.Core" Version="1.1.4" />
	</ItemGroup>

	<Import Project="KamiYomu.MultiSource.MangaThemesia.props" />

</Project>
